# Generated by Django 5.1.4 on 2024-12-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Tage',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
