# Generated by Django 5.1.4 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher_tage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Tage',
            field=models.IntegerField(default=0),
        ),
    ]
