# Generated by Django 5.1.4 on 2024-12-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teacher_tage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Tage',
        ),
    ]
