# Generated by Django 5.1.4 on 2024-12-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Sname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=20)),
            ],
        ),
    ]
